import { Metadata } from "next";

export const metadata: Metadata = {
  title: "about-web",
  description: "Generated by create next app",
};

const About=()=>{
   return(<>
         <h2>About</h2>
         <p>This component provides a concise, temperature-driven packing and safety checklist for users planning outdoor activities. It converts a single input — ambient temperature (°C) — into practical recommendations: Must-haves, Nice-to-haves, and short Precautions. The goal is to help users prepare quickly (what to wear, carry, and avoid) without overwhelming them with unnecessary detail.</p>
   </>)
}
export default About;