import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/NavBar";
import { ClerkProvider } from "@clerk/nextjs";
import ForFooter from "./_components/ForFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "comp-web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
           
              <header>
                    <nav>
                      <NavBar />
                   </nav>
            
              </header>

              <section className="dataSec">
         
                
                <article>
                    {children}
                </article>
              </section>

              <section>
                 <h2>Weather Checklist — Pack Smart by Temperature</h2>
                 <p>This tool converts a city name into an instant, temperature-based checklist: what to wear, what to carry, and key precautions. Cities you save are tied to your account and reappear after login. Weather is fetched securely from the server.</p>
                 <h3>HOW IT WORKS</h3>
               
                  <ol>
                    <li>Add/choose the city </li>
                    <li>Data comes from server of city.</li>
                    <li>And according to temperature, it gives you ideas.</li>
                  </ol>
             
                 <h3>SAVED CITIES BLURB</h3>
                 <p>Saved Cities: The cities you add are stored with your account and will be visible whenever you log in — no extra setup required.</p>

                 <h3>PRIVACY / SECURITY LINE</h3>
                 <p>We store only minimal city metadata per account. Weather API keys and external calls are handled on the server.</p>
                 <p>Practical temperature-based packing tips — fast, focused, and free for learning & personal use.</p>
                 <h3>Features</h3>
                 <ul>
                    <li>Add & Save cities per user account (persisted).</li>  
                      <li>Server-side weather fetch (secure API key).</li>
                      <li>Temperature-driven checklists (≤0, 0–10, 10–20, 20–25, 25–35, {">"}35 °C).</li>
                      <li>Responsive design (mobile & desktop).</li>        
                     <li>Lightweight presentational component — easy to style and reuse.</li>
                 </ul>
              </section>

              <footer>
               
               <div className="footer-sec">
                 <ForFooter />
                &copy; 2025 Developed by Chandrajit. All rights reserved.
                </div>
              </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
